### ISSUE TITLE
Issue with Cyrillic values

### ISSUE THREAD

**Issue by noreff** [markomilivojevic/autocomplete#1]
Hello, @markomilivojevic and thank you for a great job.

I tried your implementation and it works great. 
I have one issue which, unfortunately I didn't manage to overcome yet.

It's not working for a Cyrillic (and probably some other special characters). 

```
# That works great
Autocomplete::addTerm('cities', 'Berlin');
Autocomplete::complete('cities', 'Ber')

# That doesn't work
Autocomplete::addTerm('cities', 'Берлин');
Autocomplete::complete('cities', 'Бер')
```

If you have any thoughts on why it can be the issue please let me know and I will try to solve it and come up with PR that fixes this.

**Comment by markomilivojevic** [comment]
Hi @noreff, thanks for using this package. I've fixed the issue.
